sudo: required
services:
  - docker:


before_install:
  - docker build -t docker-react -f Dockerfile.dev .


script:
  - docker run -e CI=true docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react1"
  env: "Docker-react1-env"
  bucket_name: "elasticbeanstalk-us-east-1-702510080875"
  bucket_path: "docker-react1"
  on:
    branch: main
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
